### ISSUE TITLE
Adding custom prefixes

### ISSUE THREAD

**Issue by stefanreiterer** [OpenReqEU/cross-reference-detection#1]
There are only predefined prefixes possible - it would be nice to have custom prefixes.

Best regards,
Stefan

#opencall

**Comment by quim-motger** [comment]
This feature is planned to be included in the next release version of the cross-reference-detection service. We will create a github release once this is delivered.

**Comment by quim-motger** [comment]
This feature is now included in the latest release: https://github.com/OpenReqEU/cross-reference-detection/releases/tag/v1.0

This issue can be closed now.
